/**
 * Utility functions for Database Schema Designer & Migration Agent
 * Provides parsing, sanitization, validation, and artifact building for Prisma ORM,
 * Mermaid ERD diagrams, and SQL (PostgreSQL, MySQL) & MongoDB migration scripts.
 */

/**
 * Strips markdown code fence blocks (e.g. ```prisma ... ```)
 */
export function cleanCodeBlock(text = "") {
  if (typeof text !== "string") return "";
  return text
    .replace(/^```[a-zA-Z0-9_-]*\n?/gm, "")
    .replace(/```$/gm, "")
    .trim();
}

/**
 * Sanitizes and validates Mermaid ERD syntax to ensure client-side rendering stability.
 */
export function validateAndSanitizeMermaid(rawMermaid = "") {
  let cleaned = cleanCodeBlock(rawMermaid).trim();

  if (!cleaned || !cleaned.includes("erDiagram")) {
    const erIndex = cleaned.indexOf("erDiagram");
    if (erIndex !== -1) {
      cleaned = cleaned.substring(erIndex);
    } else {
      cleaned = `erDiagram\n    USER ||--o{ ORDER : places\n    USER {\n        string id PK\n        string email\n        string name\n    }\n    ORDER {\n        string id PK\n        string userId FK\n        float total\n        string status\n    }`;
    }
  }

  // Remove common LLM syntax flaws in Mermaid erDiagram
  const sanitizedLines = cleaned.split("\n").map(line => {
    let l = line.trimEnd();
    return l;
  });

  return sanitizedLines.join("\n");
}

/**
 * Parses multi-section output from LLM for Prisma, Mermaid, and Migrations.
 */
export function extractSchemaComponents(rawContent = "") {
  if (typeof rawContent !== "string") {
    rawContent = "";
  }

  let prismaSchema = "";
  let mermaidErd = "";
  let postgresMigration = "";
  let mysqlMigration = "";
  let mongoMigration = "";
  let explanation = "";

  // Extract PRISMA section
  const prismaMatch = rawContent.match(/===+\s*PRISMA_SCHEMA\s*===+\n([\s\S]*?)(?===\s*MERMAID_ERD|===\s*POSTGRES_MIGRATION|===\s*MYSQL_MIGRATION|===\s*MONGO_MIGRATION|$)/i)
    || rawContent.match(/```prisma\n([\s\S]*?)```/i);
  if (prismaMatch) {
    prismaSchema = cleanCodeBlock(prismaMatch[1]);
  }

  // Extract MERMAID section
  const mermaidMatch = rawContent.match(/===+\s*MERMAID_ERD\s*===+\n([\s\S]*?)(?===\s*POSTGRES_MIGRATION|===\s*MYSQL_MIGRATION|===\s*MONGO_MIGRATION|===\s*EXPLANATION|$)/i)
    || rawContent.match(/```mermaid\n([\s\S]*?)```/i);
  if (mermaidMatch) {
    mermaidErd = validateAndSanitizeMermaid(mermaidMatch[1]);
  } else {
    // Attempt fallback search for erDiagram
    const erMatch = rawContent.match(/(erDiagram[\s\S]*?)(?=```|===|$)/i);
    if (erMatch) {
      mermaidErd = validateAndSanitizeMermaid(erMatch[1]);
    }
  }

  // Extract POSTGRES SQL section
  const pgMatch = rawContent.match(/===+\s*POSTGRES_MIGRATION\s*===+\n([\s\S]*?)(?===\s*MYSQL_MIGRATION|===\s*MONGO_MIGRATION|===\s*EXPLANATION|$)/i)
    || rawContent.match(/```sql\s*(?:--\s*PostgreSQL)?\n([\s\S]*?)```/i);
  if (pgMatch) {
    postgresMigration = cleanCodeBlock(pgMatch[1]);
  }

  // Extract MYSQL SQL section
  const mysqlMatch = rawContent.match(/===+\s*MYSQL_MIGRATION\s*===+\n([\s\S]*?)(?===\s*MONGO_MIGRATION|===\s*EXPLANATION|$)/i);
  if (mysqlMatch) {
    mysqlMigration = cleanCodeBlock(mysqlMatch[1]);
  }

  // Extract MONGO section
  const mongoMatch = rawContent.match(/===+\s*MONGO_MIGRATION\s*===+\n([\s\S]*?)(?===\s*EXPLANATION|$)/i)
    || rawContent.match(/```javascript\n([\s\S]*?)```/i)
    || rawContent.match(/```js\n([\s\S]*?)```/i);
  if (mongoMatch) {
    mongoMigration = cleanCodeBlock(mongoMatch[1]);
  }

  // Extract EXPLANATION section
  const expMatch = rawContent.match(/===+\s*EXPLANATION\s*===+\n([\s\S]*?)$/i);
  if (expMatch) {
    explanation = expMatch[1].trim();
  } else {
    // Strip structured markers from explanation
    explanation = rawContent
      .replace(/===+\s*[A-Z_]+\s*===+\n[\s\S]*?(?====+|$)/g, "")
      .replace(/```[a-z]*\n[\s\S]*?```/g, "")
      .trim();
  }

  // Fallbacks if section markers were missing but content exists
  if (!mermaidErd) {
    mermaidErd = validateAndSanitizeMermaid("");
  }
  if (!prismaSchema) {
    prismaSchema = `// Prisma Schema generated by CortexAI Database Agent
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id        String   @id @default(uuid())
  email     String   @unique
  name      String?
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}`;
  }

  if (!postgresMigration) {
    postgresMigration = `-- PostgreSQL Schema Migration Script
CREATE TABLE IF NOT EXISTS "User" (
    "id" VARCHAR(36) PRIMARY KEY,
    "email" VARCHAR(255) UNIQUE NOT NULL,
    "name" VARCHAR(255),
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);`;
  }

  if (!mysqlMigration) {
    mysqlMigration = `-- MySQL Schema Migration Script
CREATE TABLE IF NOT EXISTS \`User\` (
    \`id\` VARCHAR(36) PRIMARY KEY,
    \`email\` VARCHAR(255) UNIQUE NOT NULL,
    \`name\` VARCHAR(255),
    \`createdAt\` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
    \`updatedAt\` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`;
  }

  if (!mongoMigration) {
    mongoMigration = `// MongoDB Mongoose Migration & Schema Script
import mongoose from 'mongoose';

const UserSchema = new mongoose.Schema({
  email: { type: String, required: true, unique: true, index: true },
  name: { type: String },
}, { timestamps: true });

export const User = mongoose.models.User || mongoose.model('User', UserSchema);`;
  }

  return {
    prismaSchema,
    mermaidErd,
    postgresMigration,
    mysqlMigration,
    mongoMigration,
    explanation
  };
}

/**
 * Builds standard artifact payload for the database agent response.
 */
export function buildDatabaseArtifact({
  title = "Database Schema & Migration",
  prismaSchema,
  mermaidErd,
  postgresMigration,
  mysqlMigration,
  mongoMigration,
  dialect = "postgresql"
}) {
  const files = [
    {
      name: "schema.prisma",
      content: prismaSchema,
      language: "prisma"
    },
    {
      name: "erd.mermaid",
      content: mermaidErd,
      language: "mermaid"
    },
    {
      name: "migration_postgres.sql",
      content: postgresMigration,
      language: "sql"
    },
    {
      name: "migration_mysql.sql",
      content: mysqlMigration,
      language: "sql"
    },
    {
      name: "migration_mongo.js",
      content: mongoMigration,
      language: "javascript"
    }
  ];

  return {
    id: Date.now(),
    type: "database_schema",
    title,
    dialect,
    prismaSchema,
    mermaidErd,
    postgresMigration,
    mysqlMigration,
    mongoMigration,
    files,
    createdAt: new Date().toISOString()
  };
}
